eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: ${EUREKA_SERVER_LIST}
server:
  port: ${{SERVER_PORT}:8761}
spring:
  profiles: docker
  application:
    name: service-hi