server:
  port: ${{SERVER_PORT}:8761}

spring:
  profiles: docker
  application:
    name: eureka-server
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_LIST}

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    registerWithEureka: false
#    fetchRegistry: false